# Site settings
title: Federico Vazzoler | PhD and Data Scientist 
email: vazzoler.federico@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm an experienced experimental physicist transitioning into a data science role, with strong expertise in data modeling and analysis.
  Machine learning (ML) enthusiast, with experience in applying both supervised and unsupervised ML techniques. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://federicovazzoler.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  federicovazzoler

# Build settings
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
