# Site settings
title: Federico Vazzoler | Data Scientist
logo: /assets/img/profile_picture.jpeg
description: >-
  I'm an experienced experimental physicist transitioning into a data science role, with strong expertise in data modeling and analysis.
  Machine learning (ML) enthusiast, with experience in applying both supervised and unsupervised ML techniques. 
baseurl: ""
url: "https://federicovazzoler.github.io"
github_username: federicovazzoler

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Custom configurations
navigation:
  - title: Home
    url: /
  - title: About Me
    url: /about

#show_downloads: true
#google_analytics:


